### ISSUE TITLE
About how to declare goset type

### ISSUE THREAD

**Issue by destoryccp** [amit7itz/goset#4]
Hi Amit, I have a question

I need declare a variable with goset, this code is my sture type `haproxy.ObjSet`

```go
var objSet  goset.Set[haproxy.ObjSet]
objSet = goset.NewSet[haproxy.ObjSet]()  // An error was generated
```
I read the [README.md](https://github.com/amit7itz/goset/blob/main/README.md) and annotation

the annotaion said

> // You should not call it directly, use NewSet() or FromSlice()

in this scene, How should I initial the variable

**Comment by amit7itz** [comment]
Hi @destoryccp 
The NewSet function returns a pointer, therefore your snippet should look like that:
```go
var objSet  *goset.Set[haproxy.ObjSet]
objSet = goset.NewSet[haproxy.ObjSet]() 
```
But as with anything else in go, you can also just do:
```go
objSet := goset.NewSet[haproxy.ObjSet]() 
```

You can have a look at the README & the tests file for more examples

**Comment by destoryccp** [comment]
Thank you for your reply, I try using pointer type already resolve. 😁😁
